# Generated by Django 5.0 on 2023-12-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='titulo',
            field=models.CharField(max_length=45),
        ),
    ]
