# Generated by Django 5.0 on 2023-12-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(default='default_slug', max_length=50),
            preserve_default=False,
        ),
    ]
