# Generated by Django 5.0 on 2024-01-19 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_product_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
    ]
