# Generated by Django 5.0 on 2024-01-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_remove_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cont_rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
