# Generated by Django 5.0 on 2024-01-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_remove_product_cont_rating_alter_comentario_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='dislike',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
