# Generated by Django 5.0 on 2024-01-26 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_product_subcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategoria',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='posts.subcategory'),
        ),
    ]
