# Generated by Django 5.0 on 2024-01-31 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_remove_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='posts.category', verbose_name='category'),
        ),
    ]
