# Generated by Django 5.0 on 2024-02-01 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0034_tag_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
