# Generated by Django 5.0 on 2024-02-02 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_product_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='comentarios',
            new_name='reseñas',
        ),
        migrations.AlterUniqueTogether(
            name='comentario',
            unique_together={('product', 'user')},
        ),
        migrations.RemoveField(
            model_name='product',
            name='estrellas',
        ),
        migrations.AddField(
            model_name='comentario',
            name='estrellas',
            field=models.PositiveIntegerField(choices=[(1, '1 estrella'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')], default=5),
        ),
        migrations.DeleteModel(
            name='Estrellas',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='titulo',
        ),
    ]
