# Generated by Django 5.0 on 2024-02-03 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0038_reseña_delete_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='reseñas',
            new_name='resena',
        ),
    ]
