# Generated by Django 5.0 on 2024-02-18 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0041_remove_product_vistas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='product',
            name='resena',
        ),
        migrations.DeleteModel(
            name='Reseña',
        ),
    ]
