# Generated by Django 5.0 on 2024-03-03 20:09

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0042_remove_product_comentarios_remove_product_resena_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
    ]
