# Generated by Django 5.0 on 2024-01-15 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('posts', '0017_alter_product_user'),
        ('userprofile', '0009_alter_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
        migrations.DeleteModel(
            name='Consumer',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
