# Generated by Django 5.0 on 2024-02-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdetails',
            name='comentarios',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewdetails',
            name='promedio',
            field=models.FloatField(default=0.0),
        ),
    ]
