# Generated by Django 5.0 on 2024-03-03 20:09

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_reviewdetails_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseña',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=150),
        ),
    ]
