# Generated by Django 5.0 on 2023-12-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='university',
            field=models.CharField(choices=[('EAFIT', 'Universidad EAFIT'), ('UDEA', 'Universidad de Antioquia'), ('CES', 'Universidad CES'), ('UPB', 'Universidad Pontificia Bolivariana'), ('ANDES', 'Universidad de los Andes')], default='EAFIT', max_length=5),
        ),
    ]
