# Generated by Django 5.0 on 2023-12-27 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_userprofile_university'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='university',
            new_name='universidad',
        ),
    ]
