# Generated by Django 5.0 on 2023-12-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_rename_image_userprofile_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='instagram',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
