# Generated by Django 5.0 on 2024-01-18 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_userprofile_cont_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cont_views',
        ),
    ]
