# Generated by Django 5.0 on 2024-01-18 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_remove_userprofile_cont_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cont_comments',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cont_posts',
        ),
    ]
