# Generated by Django 5.0 on 2024-01-24 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0016_userprofile_about_me'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='genero',
        ),
    ]
